[package]
name = "miniBE"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
async-trait = "0.1.88"
derive_more = "2.0.1"
json = "0.12.4"
serde = "1.0.219"
surrealdb = "2.3.0"
uuid = "1.16.0"
validator = "0.20.0"
